### ISSUE TITLE
一分钟内失败的session次数太多

### ISSUE THREAD

**Issue by wenxhwork** [lionzhong/Transmission-WebUI-Angular#1]
我使用的是transmission 2.8.4，使用本webui就会提醒这个，是只能使用2.9.2还是我的使用方法问题？

**Comment by lionzhong** [comment]
如果是session失败次数过多，应该是网络有什么问题，一分钟连续失败了5次，我就会报这个。

**Comment by lionzhong** [comment]
至于版本方面，我目前还没有去测试2.84，所以也不太清楚。如果你并不是每次都这样，那十有八九是网络原因，请求Session频繁失败。

**Comment by wenxhwork** [comment]
应该不是网络原因，rpc地址我用了白名单，写入了该服务器的独立ip地址以及localhost，但是还是不行

**Comment by lionzhong** [comment]
这个跟白名单什么的没有任何关系。

报这个错就是没法拿到session id，这是一个基本的验证，拿不到session id，接口永远不会给数据。

2.92原版的获取方式也一样，所以我不确定是否2.84能用。

**Comment by lionzhong** [comment]
另外要确定是否为网络问题，应该去看network记录，如过经常都是超时，或者请求不到数据。则可以判定为请求不到session id。或者你提供更为详细的信息，我才能帮你确定到底是怎么回事。

**Comment by wenxhwork** [comment]
找到问题了，直接访问ip:端口就能够使用，我之前使用的nginx反代就不行，但奇怪的是之前使用别的webui用nginx也可以，nginx配置中也添加了proxy_pass_header  X-Transmission-Session-Id
查看日志发现有这个问题
`Request URL:https://***/transmission/rpc?type=getSession
Request Method:POST
Status Code:405 Method Not Allowed
Remote Address:127.0.0.1:1080
Referrer Policy:no-referrer-when-downgrade`

**Comment by lionzhong** [comment]
报错信息来看，反向代理以后报错是referre缺失。应该是你的nginx设置哪里有什么问题，导致丢失了referrer，而接口要求你的http请求头里面必须有这个。也或许是因为2.84，2.92有所不同。具体的你自行研究一下吧
